In [1]:
import pandas as pd
import json
import requests
import os
from bs4 import BeautifulSoup
import re

In [2]:
url = "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(PPP)_per_capita"
res = requests.get(url)
html=res.content
soup = BeautifulSoup(html, "html.parser")

In [3]:
tables = soup.find_all("table")[1] #The second one

In [4]:
df = pd.read_html(tables.prettify())[0]
df.head()

  Country/Territory UN Region IMF  [5]  [6]       World Bank  [7]        \
  Country/Territory UN Region      Estimate  Year        Estimate  Year
0          Monaco *    Europe             —     —          190513  2019
1   Liechtenstein *    Europe             —     —          180367  2018
2      Luxembourg *    Europe        140694  2022          118360  2020
3       Singapore *      Asia        131580  2022           98526  2020
4         Ireland *    Europe        124596  2022           93612  2020

  CIA  [8]
  Estimate  Year
0   115700  2015
1   139100  2009
2   110300  2020
3    93400  2020
4    89700  2020

In [5]:
df.keys() # we want to drop the multi index to a single index

MultiIndex([('Country/Territory', 'Country/Territory'),
            (        'UN Region',         'UN Region'),
            (    'IMF  [5]  [6]',          'Estimate'),
            (    'IMF  [5]  [6]',              'Year'),
            (  'World Bank  [7]',          'Estimate'),
            (  'World Bank  [7]',              'Year'),
            (         'CIA  [8]',          'Estimate'),
            (         'CIA  [8]',              'Year')],
           )

In [9]:
df.columns=df.columns.to_flat_index()
df.columns=['Country/Territory', 'UN Region', 'IMF Estimate', 'IMF Year', 'World Bank Estimate', 'World Bank Year', 'CIA Estimate', 'CIA Year' ]
list(df.columns)
#df = df.astype({('Country/Territory', 'Country/Territory'): str}, errors='raise')

['Country/Territory',
 'UN Region',
 'IMF Estimate',
 'IMF Year',
 'World Bank Estimate',
 'World Bank Year',
 'CIA Estimate',
 'CIA Year']

In [6]:
df.columns=[(('Country/Territory', 'Country/Territory'),
            (        'UN Region',         'UN Region'),
            (    'IMF  [5]  [6]',          'Estimate'),
            (    'IMF  [5]  [6]',              'Year'),
            (  'World Bank  [7]',          'Estimate'),
            (  'World Bank  [7]',              'Year'),
            (         'CIA  [8]',          'Estimate'),
            (         'CIA  [8]',              'Year')],)]

MultiIndex([('Country/Territory', 'Country/Territory'),
            (        'UN Region',         'UN Region'),
            (    'IMF  [5]  [6]',          'Estimate'),
            (    'IMF  [5]  [6]',              'Year'),
            (  'World Bank  [7]',          'Estimate'),
            (  'World Bank  [7]',              'Year'),
            (         'CIA  [8]',          'Estimate'),
            (         'CIA  [8]',              'Year')],
           )

In [10]:
df

,Country/Territory,UN Region,IMF Estimate,IMF Year,World Bank Estimate,World Bank Year,CIA Estimate,CIA Year
0,Monaco *,Europe,—,—,190513,2019,115700,2015
1,Liechtenstein *,Europe,—,—,180367,2018,139100,2009
2,Luxembourg *,Europe,140694,2022,118360,2020,110300,2020
3,Singapore *,Asia,131580,2022,98526,2020,93400,2020
4,Ireland *,Europe,124596,2022,93612,2020,89700,2020
...,...,...,...,...,...,...,...,...
225,Somalia *,Africa,1322,2022,875.2,2020,800,2020
226,DR Congo *,Africa,1316,2022,1131,2020,1098,2019
227,Central African Republic *,Africa,1102,2022,979.6,2020,945,2019
228,South Sudan *,Africa,928,2022,1235,2015,1600,2017
229,Burundi *,Africa,856,2022,771.2,2020,752,2019

In [ ]:
df.droplevel(level=0, axis=1)

In [32]:
df

,id,node_id,name,full_name,private,owner,html_url,description,fork,url,...,license,allow_forking,is_template,web_commit_signoff_required,topics,visibility,forks,open_issues,watchers,default_branch
0,513912740,R_kgDOHqGvpA,careerweek_data-analytics-challenge,aelarabi/careerweek_data-analytics-challenge,False,"{'login': 'aelarabi', 'id': 101479986, 'node_i...",https://github.com/aelarabi/careerweek_data-an...,None,True,https://api.github.com/repos/aelarabi/careerwe...,...,None,True,False,False,[],public,0,0,0,main
1,513910930,R_kgDOHqGokg,data-analytics-challenge,fatmazaarour/data-analytics-challenge,False,"{'login': 'fatmazaarour', 'id': 103967441, 'no...",https://github.com/fatmazaarour/data-analytics...,None,True,https://api.github.com/repos/fatmazaarour/data...,...,None,True,False,False,[],public,0,0,0,main
2,513910896,R_kgDOHqGocA,data-analytics-challenge,dmitry-an-git/data-analytics-challenge,False,"{'login': 'dmitry-an-git', 'id': 103048146, 'n...",https://github.com/dmitry-an-git/data-analytic...,None,True,https://api.github.com/repos/dmitry-an-git/dat...,...,None,True,False,False,[],public,0,0,0,main
3,513910078,R_kgDOHqGlPg,data-analytics-challenge,Camille1992/data-analytics-challenge,False,"{'login': 'Camille1992', 'id': 95045702, 'node...",https://github.com/Camille1992/data-analytics-...,None,True,https://api.github.com/repos/Camille1992/data-...,...,None,True,False,False,[],public,0,0,0,main
4,503670808,R_kgDOHgVoGA,data-analytics-challenge,PauPerL/data-analytics-challenge,False,"{'login': 'PauPerL', 'id': 101154968, 'node_id...",https://github.com/PauPerL/data-analytics-chal...,DA challenge Ironhack techincal assessment pra...,True,https://api.github.com/repos/PauPerL/data-anal...,...,None,True,False,False,[],public,0,0,0,main
5,503670213,R_kgDOHgVlxQ,data-analytics-challenge,federicariva/data-analytics-challenge,False,"{'login': 'federicariva', 'id': 65666003, 'nod...",https://github.com/federicariva/data-analytics...,None,True,https://api.github.com/repos/federicariva/data...,...,None,True,False,False,[],public,0,0,0,main
6,503665629,R_kgDOHgVT3Q,data-analytics-challenge,LucasTrost/data-analytics-challenge,False,"{'login': 'LucasTrost', 'id': 102299197, 'node...",https://github.com/LucasTrost/data-analytics-c...,None,True,https://api.github.com/repos/LucasTrost/data-a...,...,None,True,False,False,[],public,0,0,0,main
7,502921765,R_kgDOHfn6JQ,data-analytics-challenge,mbarriola96/data-analytics-challenge,False,"{'login': 'mbarriola96', 'id': 101214252, 'nod...",https://github.com/mbarriola96/data-analytics-...,None,True,https://api.github.com/repos/mbarriola96/data-...,...,None,True,False,False,[],public,0,0,0,main
8,501729305,R_kgDOHefIGQ,data-analytics-challenge,HSHRU/data-analytics-challenge,False,"{'login': 'HSHRU', 'id': 45832530, 'node_id': ...",https://github.com/HSHRU/data-analytics-challenge,None,True,https://api.github.com/repos/HSHRU/data-analyt...,...,None,True,False,False,[],public,0,0,0,main
9,501701345,R_kgDOHeda4Q,data-analytics-challenge,raqclf/data-analytics-challenge,False,"{'login': 'raqclf', 'id': 101221600, 'node_id'...",https://github.com/raqclf/data-analytics-chall...,None,True,https://api.github.com/repos/raqclf/data-analy...,...,None,True,False,False,[],public,0,0,0,main
10,501668463,R_kgDOHebabw,data-analytics-challenge,romeojab/data-analytics-challenge,False,"{'login': 'romeojab', 'id': 101889763, 'node_i...",https://github.com/romeojab/data-analytics-cha...,None,True,https://api.github.com/repos/romeojab/data-ana...,...,None,True,False,False,[],public,0,0,0,main
11,501663666,R_kgDOHebHsg,data-analytics-challenge,ClaraQuer/data-analytics-challenge,False,"{'login': 'ClaraQuer', 'id': 100625408, 'node_...",https://github.com/ClaraQuer/data-analytics-ch...,None,True,https://api.github.com/repos/ClaraQuer/data-an...,...,None,True,False,False,[],public,0,0,0,main
12,501662922,R_kgDOHebEyg,data-analytics-challenge,Brenni1/data-analytics-challenge,False,"{'login': 'Brenni1', 'id': 101560303, 'node_id...",https://github.com/Brenni1/data-analytics-chal...,None,True,https://api.github.com/repos/Brenni1/data-anal...,...,None,True,False,False,[],public,0,0,0,main
13,499100339,R_kgDOHb-qsw,data-analytics-challenge,adripradm/data-analytics-challenge,False,"{'login': 'adripradm', 'id': 102025914, 'node_...",https://github.com/adripradm/data-analytics-ch...,None,True,https://api.github.com/repos/adripradm/data-an...,...,None,True,False,False,[],public,0,0,0,main
14,496632564,R_kgDOHZoC9A,data-analytics-challenge,repicao/data-analytics-challenge,False,"{'login': 'repicao', 'id': 101832800, 'node_id...",https://github.com/repicao/data-analytics-chal...,None,True,https://api.github.com/repos/repicao/data-anal...,...,None,True,False,False,[],public,0,0,0,main
15,496612929,R_kgDOHZm2QQ,data-analytics-challenge,ChristinIskander/data-analytics-challenge,False,"{'login': 'ChristinIskander', 'id': 100861650,...",https://github.com/ChristinIskander/data-analy...,None,True,https://api.github.com/repos/ChristinIskander/...,...,None,True,False,False,[],public,0,0,0,main
16,496608868,R_kgDOHZmmZA,data-analytics-challenge,jecastrom/data-analytics-challenge,False,"{'login': 'jecastrom', 'id': 63274055, 'node_i...",https://github.com/jecastrom/data-analytics-ch...,None,True,https://api.github.com/repos/jecastrom/data-an...,...,None,True,False,False,[],public,0,0,0,main
17,496605103,R_kgDOHZmXrw,data-analytics-challenge,CrisQueCris/data-analytics-challenge,False,"{'login': 'CrisQueCris', 'id': 101208657, 'nod...",https://github.com/CrisQueCris/data-analytics-...,None,True,https://api.github.com/repos/CrisQueCris/data-...,...,None,True,False,False,[],public,0,0,0,main
18,496228735,R_kgDOHZPZfw,data-analytics-challenge,jgchaparro/data-analytics-challenge,False,"{'login': 'jgchaparro', 'id': 52201191, 'node_...",https://github.com/jgchaparro/data-analytics-c...,None,True,https://api.github.com/repos/jgchaparro/data-a...,...,None,True,False,False,[],public,0,0,0,main
19,496223258,R_kgDOHZPEGg,data-analytics-challenge,agirondo/data-analytics-challenge,False,"{'login': 'agirondo', 'id': 101025495, 'node_i...",https://github.com/agirondo/data-analytics-cha...,None,True,https://api.github.com/repos/agirondo/data-ana...,...,None,True,False,False,[],public,0,0,0,main
20,495765497,R_kgDOHYzH-Q,data-analytics-challenge,NeveanK/data-analytics-challenge,False,"{'login': 'NeveanK', 'id': 90410378, 'node_id'...",https://github.com/NeveanK/data-analytics-chal...,None,True,https://api.github.com/repos/NeveanK/data-anal...,...,None,True,False,False,[],public,0,0,0,main
21,494015875,R_kgDOHXIVgw,data-analytics-challenge,nelsonlage/data-analytics-challenge,False,"{'login': 'nelsonlage', 'id': 7865477, 'node_i...",https://github.com/nelsonlage/data-analytics-c...,None,True,https://api.github.com/repos/nelsonlage/data-a...,...,None,True,False,False,[],public,0,0,0,main
22,490272222,R_kgDOHTj13g,data-analytics-challenge,isg75/data-analytics-challenge,False,"{'login': 'isg75', 'id': 42863230, 'node_id': ...",https://github.com/isg75/data-analytics-challenge,None,True,https://api.github.com/repos/isg75/data-analyt...,...,None,True,False,False,[],public,0,0,0,main
23,486649734,R_kgDOHQGvhg,data-analytics-challenge,sorianom23/data-analytics-challenge,False,"{'login': 'sorianom23', 'id': 97094998, 'node_...",https://github.com/sorianom23/data-analytics-c...,None,True,https://api.github.com/repos/sorianom23/data-a...,...,None,True,False,False,[],public,0,0,0,main
24,486590202,R_kgDOHQDG-g,data-analytics-challenge,hectorfa17/data-analytics-challenge,False,"{'login': 'hectorfa17', 'id': 97242071, 'node_...",https://github.com/hectorfa17/data-analytics-c...,None,True,https://api.github.com/repos/hectorfa17/data-a...,...,None,True,False,False,[],public,0,0,0,main
25,486589882,R_kgDOHQDFug,data-analytics-challenge,lydiaaboukhamis/data-analytics-challenge,False,"{'login': 'lydiaaboukhamis', 'id': 90446940, '...",https://github.com/lydiaaboukhamis/data-analyt...,None,True,https://api.github.com/repos/lydiaaboukhamis/d...,...,None,True,False,False,[],public,0,0,0,main
26,486588120,R_kgDOHQC-2A,data-analytics-challenge,aaronpereira92/data-analytics-challenge,False,"{'login': 'aaronpereira92', 'id': 63967678, 'n...",https://github.com/aaronpereira92/data-analyti...,None,True,https://api.github.com/repos/aaronpereira92/da...,...,None,True,False,False,[],public,0,0,0,main
27,486587500,R_kgDOHQC8bA,data-analytics-challenge,MLer76149/data-analytics-challenge,False,"{'login': 'MLer76149', 'id': 66520637, 'node_i...",https://github.com/MLer76149/data-analytics-ch...,None,True,https://api.github.com/repos/MLer76149/data-an...,...,None,True,False,False,[],public,0,0,0,main
28,486587003,R_kgDOHQC6ew,data-analytics-challenge,dru0096/data-analytics-challenge,False,"{'login': 'dru0096', 'id': 99660532, 'node_id'...",https://github.com/dru0096/data-analytics-chal...,None,True,https://api.github.com/repos/dru0096/data-anal...,...,None,True,False,False,[],public,0,0,0,main
29,477621255,R_kgDOHHfsBw,data-analytics-challenge-Solution,erin-berardi/data-analytics-challenge-Solution,False,"{'login': 'erin-berardi', 'id': 63595191, 'nod...",https://github.com/erin-berardi/data-analytics...,None,True,https://api.github.com/repos/erin-berardi/data...,...,None,True,False,False,[],public,0,0,0,main